import localFont from 'next/font/local'

const fontAwesome = localFont({
  src: [
    {
      path: '../public/fonts/fa-solid-900.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-awesome'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontAwesome.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}